#!/bin/bash
### FOR UBUNTU WE NEED INSTALL libfcgi0ldbl package ###

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd $DIR
./php-fpm-cli -r 'opcache_reset();' -connect /var/run/php/php7.0-forum-fpm.sock
popd
